baseurl = "https://pages.gitlab.io/hugo/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Tech blog"
canonifyurls  = true

DefaultContentLanguage = "fr"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 2
  [languages.fr]
    languageName = "Français"
    weight = 1

[Params]
  #subtitle = "Hugo Blog Template for GitLab Pages"
  #logo = "img/avatar-icon.png"
  favicon = "img/icon.svg"
  dateFormat = "2 January 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "Pierre-Yves Aillet"
  email = "pyaillet@gmail.com"
  gitlab = "pyaillet"
  github = "pyaillet"
  twitter = "pyaillet"
  linkedin = "pyaillet"


[[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 1

#[[menu.main]]
#    name = "About"
#    url = "page/about/"
#    weight = 3
#
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
