baseurl = "https://pages.gitlab.io/hugo/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Tech blog"
canonifyurls  = true

DefaultContentLanguage = "fr"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  #subtitle = "Hugo Blog Template for GitLab Pages"
  #logo = "img/avatar-icon.png"
  favicon = "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🤷</text></svg>"
  dateFormat = "2 January 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "Pierre-Yves Aillet"
  email = "pyaillet@gmail.com"
  gitlab = "pyaillet"
  github = "pyaillet"
  twitter = "pyaillet"
  linkedin = "pyaillet"


#[[menu.main]]
#    name = "Blog"
#    url = "post/"
#    weight = 1
#
#[[menu.main]]
#    name = "About"
#    url = "page/about/"
#    weight = 3
#
#[[menu.main]]
#    name = "Tags"
#    url = "tags"
#    weight = 3
